// config.js - REPLACE WITH YOUR ACTUAL SUPABASE CREDENTIALS
const CONFIG = {
    SUPABASE_URL: 'https://YOUR_PROJECT_ID.supabase.co',
    SUPABASE_ANON_KEY: 'YOUR_ANON_KEY'
};
export default CONFIG;
